import { Inter } from "next/font/google";
import SessionProvider from '@/config/Authentication/SessionProvider'
import { getServerSession } from "next-auth";
import Header from "@/components/Header/Header";
import './global.css'


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   keywords:'blog puglia, discover puglia, plan an holiday to puglia, holiday puglia'
// };

export default function RootLayout({ children }) {
  const session = getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Header />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
