import { Inter } from "next/font/google";
import SessionProvider from '@/config/Authentication/SessionProvider'
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import './global.css'
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   keywords:'blog puglia, discover puglia, plan an holiday to puglia, holiday puglia'
// };

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </SessionProvider>
  );
}
