import Image from "next/image";
import heroImage from '@/public/PortaAzzurraOstuni.jpg'
import styles from '@/styles/home.module.css'

export const metadata = {
  title: "HomePage",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="home">
      <div className={styles.hero}>
        <Image
          src={heroImage}
          alt="picture of Porta Azzurra in Ostuni"
          sizes='100vw'
          priority={true}
          style={{
            width: '100%',
            maxHeight: '700px',
            objectFit: 'cover'
          }}
        />
        <p>Ciao Puglia</p>
      </div>
      <div className={styles.categoryContainer}>
        <div className={styles.category}>
          category1
        </div>
        <div className={styles.category}>
          category2
        </div>
        <div className={styles.category}>
          category3
        </div>
        <div className={styles.category}>
          category4
        </div>
      </div>
    </div>
  )
}
